"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "arcazzi"
compatibility_date = "2026-02-10"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "arcazzi.bernardobordadagua.com"
custom_domain = true
