"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "arcazzi"
compatibility_date = "2026-02-10"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "arcazzi"
database_id = "67d9d77d-6f08-49fa-a736-48a2bc956f3c"
migrations_dir = "drizzle_flat"


[[routes]]
pattern = "arcazzi.bernardobordadagua.com"
custom_domain = true

